### ISSUE TITLE
Expandable ads

### ISSUE THREAD

**Issue by hgani** [m1ga/ti.dfp#14]
Hi,

We are having an issue whereby when clicking an expandable ad, instead of getting maximized to take up the full screen, it's instead getting maximized within a small view (see screenshot below).

![ad_banner1](https://cloud.githubusercontent.com/assets/417160/10746018/d6343bac-7c9a-11e5-8910-f00a07d0a313.png)

A couple of questions:
1. Has anyone encountered a similar issue?
2. Do you know if this is caused by this module or caused by other things (e.g. the native DFP SDK used by the module)?

Thanks

**Comment by jpriebe** [comment]
I believe that the DFP SDK can handle this sort of thing; it probably has something to do with the way this module was implemented.  I don't have the time to dig into this issue right now, but I welcome pull requests (ideally with working examples of special ads like expandables).
