### ISSUE TITLE
Richmedia ads

### ISSUE THREAD

**Issue by varfid** [m1ga/ti.dfp#15]
Hi, do you plan to support richmedia (Video and HTML5 ads) and new ad sizes in future releases?

Is 300x250 ad size currently supported on the current release of this module?

Thanks in advance
Pablo

**Comment by jpriebe** [comment]
300x250 works; we use that in our apps all the time.

There are no limitations regarding ad sizes; you define the ad sizes in your code and pass them into the view.

I don't know what is involved to support rich media.  Do I have to send different parameters to the PublisherAdView?  Have you tried rich media ads and found that they do not work?
