### ISSUE TITLE
bannerview in a listView

### ISSUE THREAD

**Issue by skoften** [m1ga/ti.dfp#17]
Hi Jason, we're trying to implement a bannerview in a listView. Do you think this is possible?

We've tried to add it to the header/footerview, but this view won't accept Ti.UI.SIZE for example. Best scenario would be if we could add it between the listView items, on position X.

Any ideas are welcome :-)

**Comment by jpriebe** [comment]
Sorry - I haven't ever tried that.  I have put it into a tableview, though.

**Comment by skoften** [comment]
Yeah that works, but we all work with listViews now because of performance, and if we could implement the bannerView in it, that would we great. Can't find any solution to this :-(

**Comment by jonasfunk** [comment]
Hi, I don't know if you found the answer @skoften, but you can do it by adding a global variable in your alloy.js that holds a reference to ti.dfp, like DFP = require('ti.dfp'). Then in you xml, you can do something like <View ns="DFP" id="dfp" />. Unfortunately, as it is now ti.dfp crashes when put in Listview.
