### ISSUE TITLE
Can't compile source module

### ISSUE THREAD

**Issue by skoften** [m1ga/ti.dfp#22]
For some reason I get this error when I try to build to module:

Producing [ModuleName]Bootstrap files using /Users/arjanbrinkman/Downloads/ti.dfp-master 2/android/build/generated/json/org/appcelerator/titanium/bindings/dfp.json
Generating BootstrapJS.cpp from bootstrap.js
Running the stock Android NDK ndk-build
[INFO]  Starting directory: /Users/x/Downloads/ti.dfp-master 2/android/lib
[INFO]  New directory: /Users/x/Downloads/ti.dfp-master 2/android/build/generated
[ERROR] Failed to run ndk-build
[ERROR]  
[ERROR] /Users/x/Documents/Android/android-ndk-r12b/build/core/build-local.mk:158: **\* Android NDK: Aborting.    .  Stop.

Command I used: appc ti build -p android --build-only
All paths in build.properties are valid.

**Comment by jpriebe** [comment]
What if you just run "ant" from the android directory?  That's how I build it...
