### ISSUE TITLE
Android : Crashes in listview

### ISSUE THREAD

**Issue by jonasfunk** [m1ga/ti.dfp#23]
Adding the module in a listview crashes the app. 

Alloy.js: 
`DFP = require('ti.dfp');` 

listview.xml:
`<View ns="DFP" id="dfp"/>`

Putting it outside a listview works fine.

**Comment by skoften** [comment]
On Android it doesn't seem to work in listViewItems, but you can add the view to the headerView or footerView of an section.

**Comment by darknos** [comment]
I definitely need to use DFP in listview. what can I do to help?

**Comment by darknos** [comment]
I guess I know a reason. You do createView each time when processProperties called. but with ListView all views created once and then reused using applyProperties. I'll try to fix it and propose PR later.

**Comment by skoften** [comment]
Update; headerView doens't work anymore on iOS 11.0 and SDK 6.2.2.GA :-(

@jpriebe A working example on how to use this module inside a listView would be appreciated.

**Comment by jpriebe** [comment]
We don't use ListViews in our apps; we use TableViews.  So I don't have personal experience with ListView.  I don't want to be a jerk about it, but I won't be able to spend the time researching the issues with ListViews.  Like so many things with Titanium, that has the potential to be a very deep rabbit hole...

I'll leave this issue open, with the hope that somebody will contribute a PR.  But it will not be likely to come from me.
