### ISSUE TITLE
New build for SDK 6+

### ISSUE THREAD

**Issue by skoften** [m1ga/ti.dfp#24]
Would be appreciated :-)

**Comment by TylerZubke** [comment]
Here you go: [ti.dfp-android-2.0.0.zip](https://github.com/jpriebe/ti.dfp/files/735831/ti.dfp-android-2.0.0.zip)

**Comment by m1ga** [comment]
sorry for the ping :)
closing this with https://github.com/m1ga/ti.dfp/releases/tag/android-4.0.0
