### ISSUE TITLE
NSCalendarsUsageDescription and NSBluetoothPeripheralUsageDescription

### ISSUE THREAD

**Issue by darknos** [m1ga/ti.dfp#27]
Got following from Apple:

>Missing Info.plist key - This app attempts to access privacy-sensitive data without a usage description. The app's Info.plist must contain an NSCalendarsUsageDescription key with a string value explaining to the user how the app uses this data.

>Missing Info.plist key - This app attempts to access privacy-sensitive data without a usage description. The app's Info.plist must contain an NSBluetoothPeripheralUsageDescription key with a string value explaining to the user how the app uses this data.

and found this:
http://googleadsdeveloper.blogspot.com/2016/09/use-google-mobile-ads-sdk-7110-to.html

**Comment by skoften** [comment]
Just add this to your tiapp.xml:

    <ios>
         <plist>
              <dict>
                <key>NSCalendarsUsageDescription</key>
                <string>Grant access to calendar?</string>
            </dict>
        </plist>
    </ios>

**Comment by darknos** [comment]
bad idea. Read the link above. Need to upgrade GoogleMobileAds.framework
